qsub kwave_bash.sh
qsub kwave_bash2.sh
qsub kwave_bash3.sh
qsub kwave_bash4.sh 
qsub kwave_bash5.sh
qsub kwave_bash6.sh
qsub kwave_bash7.sh
qsub kwave_bash8.sh
qsub kwave_bash9.sh
qsub kwave_bash10.sh 
qsub kwave_bash11.sh
qsub kwave_bash12.sh
qsub kwave_bash13.sh
qsub kwave_bash14.sh 
qsub kwave_bash15.sh
qsub kwave_bash16.sh
qsub kwave_basht.sh
qsub kwave_basht2.sh 
qsub kwave_basht3.sh
qsub kwave_basht4.sh
qsub kwave_bashv.sh
qsub kwave_bashv2.sh 
qsub kwave_bashv3.sh
qsub kwave_bashv4.sh

